image: node

stages:
  - test
  - js

test:
  stage: test
  script:
    - npm install -g elm-test
    - elm-test

js:  
  stage: js
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./dist/main.js
