image: node

stages:
  - test
  - build
  - ipfs

test:
  stage: test
  script:
    - npm install
    - node_modules/elm-test/bin/elm-test --compiler node_modules/elm/bin/elm --report junit > report.xml
  artifacts:
    paths:
      - report.xml
    reports:
      junit: report.xml

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./dist/cactus.js
      - ./dist/cactus.js.map
      - ./dist/style.css
      - ./dist/style.css.map

ipfs:
  image: alpine:3.7
  stage: ipfs
  script:
    - apk add python3 py3-requests
    - python3 pinata-upload.py
  only:
    - main
