image: node

stages:
  - test
  - build
  - ipfs
  - release

test:
  stage: test
  script:
    - npm install
    - node_modules/elm-test/bin/elm-test --compiler node_modules/elm/bin/elm --report junit > report.xml
  artifacts:
    paths:
      - report.xml
    reports:
      junit: report.xml

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./dist/cactus.js
      - ./dist/cactus.js.map
      - ./dist/style.css
      - ./dist/style.css.map

ipfs:
  image: alpine:3.7
  stage: ipfs
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apk add python3 py3-requests
    - python3 pinata-upload.py

release:
  stage: release
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  release:
    name: 'Release $CI_COMMIT_TAG'
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    tag_name: '$CI_COMMIT_TAG'
