image: node

stages:
  - test
  - build
  - ipfs
  - gitlab_release

test:
  stage: test
  script:
    - npm install
    - node_modules/elm-test/bin/elm-test --compiler node_modules/elm/bin/elm --report junit > report.xml
  artifacts:
    paths:
      - report.xml
    reports:
      junit: report.xml

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./dist/cactus.js
      - ./dist/cactus.js.map
      - ./dist/style.css
      - ./dist/style.css.map

ipfs:
  stage: ipfs
  image: alpine:3.7
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build
      artifacts: true
  script:
    - apk add python3 py3-requests
    - python3 pinata-upload.py "$CI_COMMIT_TAG"

gitlab_release:
  stage: gitlab_release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build
      artifacts: true
  script:
    - echo 'Making Gitlab release for $CI_COMMIT_TAG'
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Cactus Comments Web Client $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
